### ISSUE TITLE
Why is 2.7?

### ISSUE THREAD

**Issue by weiquanmao** [norishigefukushima/RandomizedRedundantDCTDenoising#2]
Thank you for releasing the code. The threshold used in the code is 2.7 times of the noise level, is 2.7 an empiric value or a theoretical one?
```
float RedundantDXTDenoise::getThreshold(float sigmaNoise)
{
    return 2.7f * sigmaNoise;
}
```

**Comment by norishigefukushima** [comment]
The magic number of 2.7 is a parameter, which is not theoritically justfyed. Denoted number in the paper of DCT denosing is 3.
http://www.ipol.im/pub/art/2011/ys-dct/article.pdf

**Comment by weiquanmao** [comment]
Thanks for your response.
